<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title><?=SITE_TITLE?></title>
	<link href="<?=URL?>/css/bootstrap.css" rel="stylesheet" media="all">        
	<link href="<?=URL?>/css/font-awesome.min.css" rel="stylesheet" media="screen" >
	<base href="/admin/" target="_blank, _self, _parent, _top">
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="?p=home"><?=SITE_NAME?></a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<li class="active"><a href="?p=home">Home</a></li>
					<li><a href="?p=usuarios">Usuarios</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">					
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Config <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="../">Sair</a></li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div>
	</nav>

	<div class="container">		
		<?php                
		$page = System\Router::pGET('p', 'home');
		System\Page::loads($page, System\Config::getDefaultRouter());        
		?>		
	</div>

	<p class="text-center small text-muted"><?=SITE_FOOTER?></p>  

	<script src="//code.jquery.com/jquery.js"></script>  
	<script src="<?=URL?>/js/bootstrap.min.js"></script>
	<script src="<?=URL?>/js/jquery-ui-1.12.js"></script>  	
</body>
</html>